

Vagrant.configure(2) do |config|

  config.vm.box = "chef/centos-6.5"
  config.vm.network "private_network", ip: "192.168.33.77"
  config.vm.synced_folder "/Users/jakeb/projects/MyApp/target","/webapp"

  config.vm.provision "chef_solo" do |chef|
    chef.roles_path = "chef/roles"
    chef.cookbooks_path = "chef/cookbooks"
    chef.add_role "java-dev-workstation"
  end

end
